### ISSUE TITLE
Wrap up

### ISSUE THREAD

**Issue by dheim** [dheim/medone#7]
- Styling / touch and feel: the application should be elegant (or at least less ugly than it is now)
- When a nurse logs on, she shouldn't see the prescription form (when she tries to submit a prescription, the service will throw a 403 error)
- When a user without a token or with an expired token navigates to any route, he should be redirected to the login page
- Prescription form validation: Each prescription needs a drug, a dosage scheme and at least one disposal

**Comment by tho89** [comment]
> When a nurse logs on, she shouldn't see the prescription form (when she tries to submit a prescription, the service will throw a 403 error)
done

> When a user without a token or with an expired token navigates to any route, he should be redirected to the login page
done

**Comment by tho89** [comment]
> Prescription form validation: Each prescription needs a drug, a dosage scheme and at least one disposal

done
